### ISSUE TITLE
request param is missing in authenticate method

### ISSUE THREAD

**Issue by bootrino** [sirodoht/opencult.com#72]
Note the authenticate function here: 

https://github.com/skorokithakis/django-tokenauth/blob/628216a777173160da0cf798ee14ebf0172208ea/tokenauth/auth_backends.py#L15

has a different signature to the authenticate function in opencult.

The request param is missing in opencult and needs to be added both to the class here:

https://github.com/sirodoht/opencult.com/blob/e614e214494d0c2fba48f5ba28634498685303c7/main/auth_backends.py#L24

and also added to the place where the authenticate method is called which is in here:

https://github.com/sirodoht/opencult.com/blob/e614e214494d0c2fba48f5ba28634498685303c7/main/views.py#L101

it used to work then I think it broke when I upgraded to the latest Django but I'm not sure.

**Comment by sirodoht** [comment]
Yes, this is indeed a breaking change from Django 1.11 -> Django 2.0. 

There is another one regarding the Django sign method. Here is a [detailed explanation](https://github.com/skorokithakis/django-tokenauth/pull/1#issue-157116060)

I haven't updated opencult to Django 2.0 yet. Once I do, I will also fix these issues. Feel free to submit a PR though!
